version: '3.8'
services:
  app:
    build: .
    ports:
      - '2020:2020'
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  test:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm test