version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: faghihy
      POSTGRES_PASSWORD: 2020
      POSTGRES_DB: twperm
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - '2020:2020'
    depends_on:
      - postgres

volumes:
  postgres_data: